local _, EasyFishing = ...
EasyFishing = EasyFishing or _G.EasyFishing or {}
_G.EasyFishing = EasyFishing

EasyFishing.Data = {
    MAIN_HAND_SLOT = 16,
    FISHING_ITEM_CLASS_ID = 2,
    FISHING_POLE_SUBCLASS_IDS = {
        [20] = true,
        [25] = true,
    },
    FISHING_SPELL_IDS = { 7620, 131474 },
    LURES = {
        { id = 6529, minimumSkill = 1 },
        { id = 6530, minimumSkill = 50 },
        { id = 6811, minimumSkill = 50 },
        { id = 6532, minimumSkill = 100 },
        { id = 7307, minimumSkill = 100 },
        { id = 6533, minimumSkill = 100 },
    },
    FISHING_RANKS = {
        {
            name = "Apprentice",
            range = "1-75",
            minimumSkill = 1,
            nextTraining = 75,
            detail = "Train with any Fishing trainer. Starter zones reach a 100% catch rate at skill 25.",
        },
        {
            name = "Journeyman",
            range = "75-150",
            minimumSkill = 75,
            nextTraining = 150,
            detail = "Train with any Fishing trainer. Capital cities reach a 100% catch rate at skill 75.",
        },
        {
            name = "Expert",
            range = "150-225",
            minimumSkill = 150,
            nextTraining = 225,
            detail = "Buy The Bass and You from Old Man Heming in Booty Bay (1g). In Dustwallow Marsh and Stranglethorn Vale, your Fishing skill plus gear and lure bonuses must reach 225 for a 100% catch rate.",
        },
        {
            name = "Artisan",
            range = "225-300",
            minimumSkill = 225,
            detail = "Nat Pagle, Angler Extreme requires character level 35 and Fishing 225. A complete 225-300 route is not documented.",
        },
    },
    FISHING_TRAINERS = {
        { name = "Androl Oakhand", side = "Alliance", location = "Rut'theran Village", zone = "Teldrassil", x = 56, y = 93.6 },
        { name = "Arnold Leland", side = "Alliance", location = "Trade District canal", zone = "Stormwind", x = 55, y = 69.6 },
        { name = "Astaia", side = "Alliance", location = "Temple Gardens", zone = "Darnassus", x = 47.6, y = 56.6 },
        { name = "Brannock", side = "Alliance", location = "Feathermoon Stronghold", zone = "Feralas", x = 32.2, y = 41.6 },
        { name = "Donald Rabonne", side = "Alliance", location = "Southshore", zone = "Hillsbrad Foothills", x = 50.6, y = 61 },
        { name = "Grimnur Stonebrand", side = "Alliance", location = "Forlorn Cavern", zone = "Ironforge", x = 48.4, y = 6.4 },
        { name = "Harold Riggs", side = "Alliance", location = "Menethil Harbor", zone = "Wetlands", x = 8.2, y = 58.6 },
        { name = "Lee Brown", side = "Alliance", location = "Goldshire", zone = "Elwynn Forest", x = 47.6, y = 62.2 },
        { name = "Matthew Hooper", side = "Alliance", location = "Lakeshire", zone = "Redridge Mountains", x = 26.8, y = 50.4 },
        { name = "Paxton Ganter", side = "Alliance", location = "Brewnall Village", zone = "Dun Morogh", x = 35.6, y = 40.4 },
        { name = "Warg Deepwater", side = "Alliance", location = "Thelsamar", zone = "Loch Modan", x = 40.6, y = 39.6 },
        { name = "Armand Cromwell", side = "Horde", location = "Magic Quarter", zone = "Undercity", x = 80.8, y = 31.2 },
        { name = "Clyde Kellen", side = "Horde", location = "Brightwater Lake", zone = "Tirisfal Glades", x = 67.2, y = 51 },
        { name = "Kah Mistrunner", side = "Horde", location = "Middle Tier", zone = "Thunder Bluff", x = 56, y = 46.8 },
        { name = "Katoom the Angler", side = "Horde", location = "Revantusk Village", zone = "The Hinterlands", x = 80.2, y = 81.4 },
        { name = "Kil'Hiwana", side = "Horde", location = "South of Blackfathom Deeps", zone = "Ashenvale", x = 10.8, y = 33.6 },
        { name = "Lau'Tiki", side = "Horde", location = "South of Sen'jin Village", zone = "Durotar", x = 53.2, y = 81.6 },
        { name = "Lui'Mala", side = "Horde", location = "Shadowprey Village", zone = "Desolace", x = 22.6, y = 72.6 },
        { name = "Lumak", side = "Horde", location = "Valley of Honor", zone = "Orgrimmar", x = 69.8, y = 29.6 },
        { name = "Uthan Stillwater", side = "Horde", location = "Bloodhoof Village", zone = "Mulgore", x = 44.6, y = 60.6 },
        { name = "Myizz Luckycatch", side = "Both", location = "Booty Bay", zone = "Stranglethorn Vale", x = 27.6, y = 77 },
        { name = "Fenn Fairweather", side = "Neutral", location = "Shen'dar Village", zone = "Zephras Isle", x = 45, y = 48.4 },
        { name = "Baelann Swiftcurrent", side = "Neutral", location = "Valanaar", zone = "Zephras Isle", x = 63.2, y = 75.6 },
        { name = "Krix", side = "Neutral", location = "Powderfuse Port", zone = "Riverglades", x = 79.2, y = 54.6 },
    },
    CHAT_GEAR_SLOT_IDS = { 16, 1, 10, 8, 17 },
}