local _, EasyFishing = ...
EasyFishing = EasyFishing or _G.EasyFishing or {}
_G.EasyFishing = EasyFishing

EasyFishing.Data = {
    MAIN_HAND_SLOT = 16,
    FISHING_ITEM_CLASS_ID = 2,
    FISHING_POLE_SUBCLASS_IDS = {
        [20] = true,
        [25] = true,
    },
    FISHING_SPELL_IDS = { 7620, 131474 },
    LURES = {
        { id = 6529, name = "Shiny Bauble", bonus = 25, minimumSkill = 1 },
        { id = 6530, name = "Nightcrawlers", bonus = 50, minimumSkill = 50 },
        { id = 6811, name = "Aquadynamic Fish Lens", bonus = 50, minimumSkill = 50 },
        { id = 6532, name = "Bright Baubles", bonus = 75, minimumSkill = 100 },
        { id = 7307, name = "Flesh Eating Worm", bonus = 75, minimumSkill = 100 },
        { id = 6533, name = "Aquadynamic Fish Attractor", bonus = 100, minimumSkill = 100 },
    },
    FISHING_CAMP_ITEMS = {
        {
            id = 279967,
            name = "Fish Bowl",
            craftSkill = 20,
            source = "Trainer",
            details = "Requires Fishing 20 to use and a nearby campfire. Grants nearby players +8% stats; does not stack with Blessing of Kings. Shares the 1-hour campsite cooldown.",
            recipe = "Raw Brilliant Smallfish + Empty Vial",
        },
        {
            id = 279965,
            name = "Fishing Rack",
            craftSkill = 140,
            source = "Blueprint",
            details = "Requires Fishing 140 to use and a nearby campfire. Allows uncommon fish and provides Fishing lures for 1 hour. Includes Fish Bowl effects and may replace a Fish Bowl. Shares the 1-hour campsite cooldown.",
            recipe = "2 Simple Wood + Crystal Vial + 2 Raw Mithril Head Trout",
        },
        {
            id = 279966,
            name = "Fishing Hut",
            craftSkill = 300,
            source = "Blueprint",
            details = "Requires Fishing 300 to use and a nearby campfire. Allows rare fish and provides Fishing lures for 1 hour. Includes Fish Bowl effects and may replace a Fish Bowl. Shares the 1-hour campsite cooldown.",
            recipe = "5 Simple Wood + 2 Bolt of Runecloth + Seasonal Fish Steaks",
        },
    },
    FISHING_RANKS = {
        {
            name = "Apprentice",
            range = "1-75",
            minimumSkill = 1,
            maximumSkill = 75,
            nextTraining = 75,
            detail = "Train with any Fishing trainer. Starter zones reach a 100% catch rate at skill 25.",
        },
        {
            name = "Journeyman",
            range = "75-150",
            minimumSkill = 75,
            maximumSkill = 150,
            nextTraining = 150,
            detail = "Train with any Fishing trainer. Capital cities reach a 100% catch rate at skill 75.",
        },
        {
            name = "Expert",
            range = "150-225",
            minimumSkill = 150,
            maximumSkill = 225,
            nextTraining = 225,
            detail = "Buy The Bass and You from Old Man Heming in Booty Bay (1g). Reach 225 skill with gear and lures for 100% catches in Dustwallow Marsh or Stranglethorn Vale.",
        },
        {
            name = "Artisan",
            range = "225-300",
            minimumSkill = 225,
            maximumSkill = 300,
            detail = "Nat Pagle, Angler Extreme requires character level 35 and Fishing 225. A complete 225-300 route is not documented.",
        },
    },
    FISHING_NPCS = {
        { name = "Androl Oakhand", role = "Fisherman", level = 37, side = "Alliance", location = "Rut'theran Village", zone = "Teldrassil", x = 56, y = 93.6 },
        { name = "Arnold Leland", role = "Fishing Trainer", level = 35, side = "Alliance", location = "Trade District canal", zone = "Stormwind", x = 55, y = 69.6 },
        { name = "Astaia", role = "Fishing Trainer", level = 35, side = "Alliance", location = "Temple Gardens", zone = "Darnassus", x = 47.6, y = 56.6 },
        { name = "Baelann Swiftcurrent", role = "Fisher", level = 10, side = "Neutral", location = "Valanaar", zone = "Zephras Isle", x = 63.2, y = 75.6 },
        { name = "Brannock", role = "Fisherman", level = 52, side = "Alliance", location = "Feathermoon Stronghold", zone = "Feralas", x = 32.2, y = 41.6 },
        { name = "Clyde Kellen", role = "Fisherman", level = 16, side = "Horde", location = "Brightwater Lake", zone = "Tirisfal Glades", x = 67.2, y = 51 },
        { name = "Donald Rabonne", role = "Fisherman", level = 31, side = "Alliance", location = "Southshore", zone = "Hillsbrad Foothills", x = 50.6, y = 61 },
        { name = "Fenn Fairweather", role = "Fisherman", level = 5, side = "Neutral", location = "Shen'dar Village", zone = "Zephras Isle", x = 45, y = 48.4 },
        { name = "Grimnur Stonebrand", role = "Fishing Trainer", level = 35, side = "Alliance", location = "Forlorn Cavern", zone = "Ironforge", x = 48.4, y = 6.4 },
        { name = "Harold Riggs", role = "Fishing Trainer", level = 25, side = "Alliance", location = "Menethil Harbor", zone = "Wetlands", x = 8.2, y = 58.6 },
        { name = "Hunter Moore", role = "Fisherman", level = 31, side = "Alliance", location = "Coordinates not listed", zone = "Hillsbrad Foothills" },
        { name = "Kah Mistrunner", role = "Fishing Trainer", level = 45, side = "Horde", location = "Middle Tier", zone = "Thunder Bluff", x = 56, y = 46.8 },
        { name = "Katoom the Angler", role = "Fishing Trainer & Supplies", level = 42, side = "Horde", location = "Revantusk Village", zone = "The Hinterlands", x = 80.2, y = 81.4 },
        { name = "Kil'Hiwana", role = "Fisherman", level = 30, side = "Horde", location = "South of Blackfathom Deeps", zone = "Ashenvale", x = 10.8, y = 33.6 },
        { name = "Krix", role = "Superior Fisherman", level = 43, side = "Neutral", location = "Powderfuse Port", zone = "Riverglades", x = 79.2, y = 54.6 },
        { name = "Lau'Tiki", role = "Fisherman", level = 14, side = "Horde", location = "South of Sen'jin Village", zone = "Durotar", x = 53.2, y = 81.6 },
        { name = "Lee Brown", role = "Fisherman", level = 8, side = "Alliance", location = "Goldshire", zone = "Elwynn Forest", x = 47.6, y = 62.2 },
        { name = "Lui'Mala", role = "Fisherman", level = 30, side = "Horde", location = "Shadowprey Village", zone = "Desolace", x = 22.6, y = 72.6 },
        { name = "Lumak", role = "Fishing Trainer", level = 35, side = "Horde", location = "Valley of Honor", zone = "Orgrimmar", x = 69.8, y = 29.6 },
        { name = "Matthew Hooper", role = "Fishing Trainer", level = 10, side = "Alliance", location = "Lakeshire", zone = "Redridge Mountains", x = 26.8, y = 50.4 },
        { name = "Myizz Luckycatch", role = "Superior Fisherman", level = 43, side = "Both", location = "Booty Bay", zone = "Stranglethorn Vale", x = 27.6, y = 77 },
        { name = "Paxton Ganter", role = "Fisherman", level = 10, side = "Alliance", location = "Brewnall Village", zone = "Dun Morogh", x = 35.6, y = 40.4 },
        { name = "Uthan Stillwater", role = "Fisherman", level = 14, side = "Horde", location = "Bloodhoof Village", zone = "Mulgore", x = 44.6, y = 60.6 },
        { name = "Warg Deepwater", role = "Fisherman", level = 15, side = "Alliance", location = "Thelsamar", zone = "Loch Modan", x = 40.6, y = 39.6 },
        { name = "Armand Cromwell", role = "Fishing Trainer", level = 35, side = "Horde", location = "Magic Quarter", zone = "Undercity", x = 80.8, y = 31.2 },
    },
    FISHING_ABILITIES = {
        {
            id = 43308,
            name = "Find Fish",
            minimumSkill = 1,
            cooldown = "1.5 sec",
            details = "Nearby fishing pools appear on the minimap while this effect is active.",
        },
    },
    FISHING_BOOSTS = {
        { id = 12225, name = "Blump Family Fishing Pole", category = "Pole", bonus = 3, minimumSkill = 1, source = "The Family and the Fishing Pole" },
        { id = 6365, name = "Strong Fishing Pole", category = "Pole", bonus = 5, minimumSkill = 10, source = "Fishing Supplies vendor" },
        { id = 6367, name = "Big Iron Fishing Pole", category = "Pole", bonus = 20, minimumSkill = 100, source = "Shellfish Trap, Desolace; tradable" },
        { id = 19022, name = "Nat Pagle's Extreme Angler FC-5000", displayName = "Extreme Angler FC-5000", category = "Pole", bonus = 25, minimumSkill = 100, side = "Horde", source = "Snapjaws, Mon!" },
        { id = 19970, name = "Arcanite Fishing Pole", category = "Pole", bonus = 35, minimumSkill = 300, source = "Master Angler tournament" },
        { id = 19972, name = "Lucky Fishing Hat", category = "Gear", bonus = 5, minimumSkill = 1, source = "Keefer's Angelfish quest" },
        { id = 19969, name = "Nat Pagle's Extreme Anglin' Boots", displayName = "Extreme Anglin' Boots", category = "Gear", bonus = 5, minimumSkill = 1, source = "Brownell's Blue Striped Racer quest" },
        { id = 19971, name = "High Test Eternium Fishing Line", displayName = "Eternium Fishing Line", category = "Gear", bonus = 5, minimumSkill = 1, source = "Dezian Queenfish quest" },
        { id = 13620, iconType = "spell", name = "Enchant Gloves - Fishing", category = "Enchant", bonus = 2, minimumSkill = 1, source = "Enchanting" },
    },
    FISHING_QUEST_REWARDS = {
        { questID = 1580, name = "Electropellers", reward = "20 Aquadynamic Fish Lenses", rewardName = "Aquadynamic Fish Lens", rewardValue = "x20", rewardItemID = 6811, sourceLabel = "Electropellers", details = "Character level 12 and Fishing skill 10." },
        { questID = 1141, name = "The Family and the Fishing Pole", reward = "Blump Family Fishing Pole (+3 Fishing)", rewardName = "Blump Family Fishing Pole", rewardValue = "+3 Fishing", rewardItemID = 12225, sourceLabel = "Family and the Fishing Pole", details = "Fishing pole quest in Darkshore." },
        { questID = 7815, name = "Snapjaws, Mon!", reward = "Nat Pagle's Extreme Angler FC-5000 (+25 Fishing)", rewardName = "Extreme Angler FC-5000", rewardValue = "+25 Fishing", rewardItemID = 19022, side = "Horde", sourceLabel = "Snapjaws, Mon!", details = "Horde quest in the Hinterlands." },
        { questID = 8221, name = "Rare Fish: Keefer's Angelfish", reward = "Lucky Fishing Hat (+5 Fishing)", rewardName = "Lucky Fishing Hat", rewardValue = "+5 Fishing", rewardItemID = 19972, sourceLabel = "Keefer's Angelfish quest", details = "Reward for turning in Keefer's Angelfish." },
        { questID = 8225, name = "Rare Fish: Brownell's Blue Striped Racer", reward = "Nat Pagle's Extreme Anglin' Boots (+5 Fishing)", rewardName = "Extreme Anglin' Boots", rewardValue = "+5 Fishing", rewardItemID = 19969, sourceLabel = "Brownell's Racer quest", details = "Reward for turning in Brownell's Blue Striped Racer." },
        { questID = 8224, name = "Rare Fish: Dezian Queenfish", reward = "High Test Eternium Fishing Line (+5 Fishing)", rewardName = "Eternium Fishing Line", rewardValue = "+5 Fishing", rewardItemID = 19971, sourceLabel = "Dezian Queenfish quest", details = "Reward for turning in Dezian Queenfish." },
        { questID = 8193, name = "Master Angler", reward = "Arcanite Fishing Pole or Hook of the Master Angler", rewardName = "Arcanite Fishing Pole", rewardValue = "+35 Fishing", rewardItemID = 19970, alternateRewardItemID = 19979, sourceLabel = "Weekly; choose pole or Hook", weekly = true, details = "Level 60 weekly Stranglethorn Vale tournament; the first 50 players can win." },
        { questID = 6607, name = "Nat Pagle, Angler Extreme", reward = "Artisan Fishing", rewardName = "Artisan Fishing", rewardValue = "Training", rewardSpellID = 18248, sourceLabel = "Artisan quest", requiredSkill = 225, requiredCharacterLevel = 35, details = "Catch four unique fish that are available only while on the quest." },
    },
    CHAT_GEAR_SLOT_IDS = { 16, 1, 10, 8, 17 },
}