local _, EasyFishing = ...
EasyFishing = EasyFishing or _G.EasyFishing or {}
_G.EasyFishing = EasyFishing

EasyFishing.Data = {
    MAIN_HAND_SLOT = 16,
    FISHING_ITEM_CLASS_ID = 2,
    FISHING_POLE_SUBCLASS_IDS = {
        [20] = true,
        [25] = true,
    },
    FISHING_SPELL_IDS = { 7620, 131474 },
    LURES = {
        { id = 6529, name = "Shiny Bauble", bonus = 25, minimumSkill = 1 },
        { id = 6530, name = "Nightcrawlers", bonus = 50, minimumSkill = 50 },
        { id = 6811, name = "Aquadynamic Fish Lens", bonus = 50, minimumSkill = 50 },
        { id = 6532, name = "Bright Baubles", bonus = 75, minimumSkill = 100 },
        { id = 7307, name = "Flesh Eating Worm", bonus = 75, minimumSkill = 100 },
        { id = 6533, name = "Aquadynamic Fish Attractor", bonus = 100, minimumSkill = 100 },
    },
    FISHING_CAMP_ITEMS = {
        {
            id = 279967,
            name = "Fish Bowl",
            craftSkill = 20,
            source = "Trainer",
            details = "Requires Fishing 20 to use and a nearby campfire. Grants nearby players +8% stats; does not stack with Blessing of Kings. Shares the 1-hour campsite cooldown.",
            recipe = "Raw Brilliant Smallfish + Empty Vial",
        },
        {
            id = 279965,
            name = "Fishing Rack",
            craftSkill = 140,
            source = "Blueprint",
            details = "Requires Fishing 140 to use and a nearby campfire. Allows uncommon fish and provides Fishing lures for 1 hour. Includes Fish Bowl effects and may replace a Fish Bowl. Shares the 1-hour campsite cooldown.",
            recipe = "2 Simple Wood + Crystal Vial + 2 Raw Mithril Head Trout",
        },
        {
            id = 279966,
            name = "Fishing Hut",
            craftSkill = 300,
            source = "Blueprint",
            details = "Requires Fishing 300 to use and a nearby campfire. Allows rare fish and provides Fishing lures for 1 hour. Includes Fish Bowl effects and may replace a Fish Bowl. Shares the 1-hour campsite cooldown.",
            recipe = "5 Simple Wood + 2 Bolt of Runecloth + Seasonal Fish Steaks",
        },
    },
    FISHING_RANKS = {
        {
            name = "Apprentice",
            range = "1-75",
            minimumSkill = 1,
            maximumSkill = 75,
            nextTraining = 75,
            detail = "Train with any Fishing trainer. Starter zones reach a 100% catch rate at skill 25.",
        },
        {
            name = "Journeyman",
            range = "75-150",
            minimumSkill = 75,
            maximumSkill = 150,
            nextTraining = 150,
            detail = "Train with any Fishing trainer. Capital cities reach a 100% catch rate at skill 75.",
        },
        {
            name = "Expert",
            range = "150-225",
            minimumSkill = 150,
            maximumSkill = 225,
            nextTraining = 225,
            detail = "Buy The Bass and You from Old Man Heming in Booty Bay (1g). Reach 225 skill with gear and lures for 100% catches in Dustwallow Marsh or Stranglethorn Vale.",
        },
        {
            name = "Artisan",
            range = "225-300",
            minimumSkill = 225,
            maximumSkill = 300,
            detail = "Nat Pagle, Angler Extreme requires character level 35 and Fishing 225. A complete 225-300 route is not documented.",
        },
    },
    FISHING_NPCS = {
        { name = "Androl Oakhand", role = "Fisherman", level = 37, side = "Alliance", location = "Rut'theran Village", zone = "Teldrassil", mapID = 1438, x = 56, y = 93.6 },
        { name = "Arnold Leland", role = "Fishing Trainer", level = 35, side = "Alliance", location = "Trade District canal", zone = "Stormwind", mapID = 1453, x = 55, y = 69.6 },
        { name = "Astaia", role = "Fishing Trainer", level = 35, side = "Alliance", location = "Temple Gardens", zone = "Darnassus", mapID = 1457, x = 47.6, y = 56.6 },
        { name = "Baelann Swiftcurrent", role = "Fisher", level = 10, side = "Neutral", location = "Valanaar", zone = "Zephras Isle", mapID = 16593, x = 63.2, y = 75.6 },
        { name = "Brannock", role = "Fisherman", level = 52, side = "Alliance", location = "Feathermoon Stronghold", zone = "Feralas", mapID = 1444, x = 32.2, y = 41.6 },
        { name = "Clyde Kellen", role = "Fisherman", level = 16, side = "Horde", location = "Brightwater Lake", zone = "Tirisfal Glades", mapID = 1420, x = 67.2, y = 51 },
        { name = "Donald Rabonne", role = "Fisherman", level = 31, side = "Alliance", location = "Southshore", zone = "Hillsbrad Foothills", mapID = 1424, x = 50.6, y = 61 },
        { name = "Fenn Fairweather", role = "Fisherman", level = 5, side = "Neutral", location = "Shen'dar Village", zone = "Zephras Isle", mapID = 16593, x = 45, y = 48.4 },
        { name = "Fishbot 5000", role = "Rare Fish Turn-In", level = 30, levelRange = "10-30", side = "Neutral", location = "Booty Bay (tournament)", zone = "Stranglethorn Vale" },
        { name = "Gikkix", role = "Fish and Cooking Vendor", level = 40, side = "Neutral", location = "Steamwheedle Port", zone = "Tanaris", mapID = 1446, x = 66.6, y = 22.2 },
        { name = "Grimnur Stonebrand", role = "Fishing Trainer", level = 35, side = "Alliance", location = "Forlorn Cavern", zone = "Ironforge", mapID = 1455, x = 48.4, y = 6.4 },
        { name = "Gubber Blump", role = "Fishing Trainer & Supplies", level = 15, side = "Alliance", location = "Auberdine", zone = "Darkshore", mapID = 1439, x = 36.1, y = 44.9 },
        { name = "Harn Longcast", role = "Fishing Supplies", level = 30, levelRange = "1-30", side = "Horde", location = "Bloodhoof Village (north bridge)", zone = "Mulgore", mapID = 1412, x = 47.4, y = 55.4 },
        { name = "Harold Riggs", role = "Fishing Trainer", level = 25, side = "Alliance", location = "Menethil Harbor", zone = "Wetlands", mapID = 1437, x = 8.2, y = 58.6 },
        { name = "Hunter Moore", role = "Fisherman", level = 31, side = "Alliance", location = "Southshore Coast", zone = "Hillsbrad Foothills", mapID = 1424, x = 51.0, y = 59.8 },
        { name = "Jang", role = "Tastyfish Turn-In", level = 30, levelRange = "10-30", side = "Neutral", location = "Booty Bay (tournament)", zone = "Stranglethorn Vale" },
        { name = "Kah Mistrunner", role = "Fishing Trainer", level = 45, side = "Horde", location = "Middle Tier", zone = "Thunder Bluff", mapID = 1456, x = 56, y = 46.8 },
        { name = "Katoom the Angler", role = "Fishing Trainer & Supplies", level = 42, side = "Horde", location = "Revantusk Village", zone = "The Hinterlands", mapID = 1425, x = 80.2, y = 81.4 },
        { name = "Kilxx", role = "Fish and Fishing Supplies Vendor", level = 30, levelRange = "5-30", side = "Neutral", location = "Ratchet", zone = "The Barrens", mapID = 1413, x = 62.8, y = 38.2 },
        { name = "Kil'Hiwana", role = "Fisherman", level = 30, side = "Horde", location = "South of Blackfathom Deeps", zone = "Ashenvale", mapID = 1440, x = 10.8, y = 33.6 },
        { name = "Krix", role = "Superior Fisherman", level = 43, side = "Neutral", location = "Powderfuse Port", zone = "Riverglades", mapID = 16594, x = 79.2, y = 54.6 },
        { name = "Lau'Tiki", role = "Fisherman", level = 14, side = "Horde", location = "South of Sen'jin Village", zone = "Durotar", mapID = 1411, x = 53.2, y = 81.6 },
        { name = "Lee Brown", role = "Fisherman", level = 8, side = "Alliance", location = "Goldshire", zone = "Elwynn Forest", mapID = 1429, x = 47.6, y = 62.2 },
        { name = "Lui'Mala", role = "Fisherman", level = 30, side = "Horde", location = "Shadowprey Village", zone = "Desolace", mapID = 1443, x = 22.6, y = 72.6 },
        { name = "Lumak", role = "Fishing Trainer", level = 35, side = "Horde", location = "Valley of Honor", zone = "Orgrimmar", mapID = 1454, x = 69.8, y = 29.6 },
        { name = "Matthew Hooper", role = "Fishing Trainer", level = 10, side = "Alliance", location = "Lakeshire", zone = "Redridge Mountains", mapID = 1433, x = 26.8, y = 50.4 },
        { name = "Myizz Luckycatch", role = "Superior Fisherman", level = 43, side = "Both", location = "Booty Bay", zone = "Stranglethorn Vale", mapID = 1434, x = 27.6, y = 77 },
        { name = "Nat Pagle", role = "Fishing Trainer & Questgiver", level = 35, side = "Both", location = "Nat's Landing", zone = "Dustwallow Marsh", mapID = 1445, x = 58.6, y = 60.2 },
        { name = "Old Man Heming", role = "Fishing Supplies & Expert Book", level = 30, levelRange = "10-30", side = "Neutral", location = "The Happy Bobber (lower platform)", zone = "Stranglethorn Vale", mapID = 1434, x = 27.7, y = 76.6 },
        { name = "Paxton Ganter", role = "Fisherman", level = 10, side = "Alliance", location = "Brewnall Village", zone = "Dun Morogh", mapID = 1426, x = 35.6, y = 40.4 },
        { name = "Riggle Bassbait", role = "Fishing Tournament Organizer", level = 30, levelRange = "10-30", side = "Neutral", location = "Booty Bay docks", zone = "Stranglethorn Vale" },
        { name = "Uthan Stillwater", role = "Fisherman", level = 14, side = "Horde", location = "Bloodhoof Village", zone = "Mulgore", mapID = 1412, x = 44.6, y = 60.6 },
        { name = "Warg Deepwater", role = "Fisherman", level = 15, side = "Alliance", location = "Thelsamar", zone = "Loch Modan", mapID = 1432, x = 40.6, y = 39.6 },
        { name = "Wigcik", role = "Fish Vendor", level = 30, levelRange = "10-30", side = "Neutral", location = "Booty Bay", zone = "Stranglethorn Vale", mapID = 1434, x = 27.4, y = 76.8 },
        { name = "Armand Cromwell", role = "Fishing Trainer", level = 35, side = "Horde", location = "Magic Quarter", zone = "Undercity", mapID = 1458, x = 80.8, y = 31.2 },
    },
    FISHING_ABILITIES = {
        {
            id = 43308,
            name = "Find Fish",
            minimumSkill = 1,
            cooldown = "1.5 sec",
            details = "Nearby fishing pools appear on the minimap while this effect is active.",
        },
    },
    FISHING_BOOSTS = {
        { id = 12225, name = "Blump Family Fishing Pole", category = "Pole", bonus = 3, minimumSkill = 1, source = "The Family and the Fishing Pole" },
        { id = 6365, name = "Strong Fishing Pole", category = "Pole", bonus = 5, minimumSkill = 10, source = "Fishing Supplies vendor" },
        { id = 6367, name = "Big Iron Fishing Pole", category = "Pole", bonus = 20, minimumSkill = 100, source = "Shellfish Trap, Desolace; tradable" },
        { id = 19022, name = "Nat Pagle's Extreme Angler FC-5000", displayName = "Extreme Angler FC-5000", category = "Pole", bonus = 25, minimumSkill = 100, side = "Horde", source = "Snapjaws, Mon!" },
        { id = 19970, name = "Arcanite Fishing Pole", category = "Pole", bonus = 35, minimumSkill = 300, source = "Master Angler tournament" },
        { id = 19972, name = "Lucky Fishing Hat", category = "Gear", bonus = 5, minimumSkill = 1, source = "Keefer's Angelfish quest" },
        { id = 19969, name = "Nat Pagle's Extreme Anglin' Boots", displayName = "Extreme Anglin' Boots", category = "Gear", bonus = 5, minimumSkill = 1, source = "Brownell's Blue Striped Racer quest" },
        { id = 19971, name = "High Test Eternium Fishing Line", displayName = "Eternium Fishing Line", category = "Gear", bonus = 5, minimumSkill = 1, source = "Dezian Queenfish quest" },
        { id = 13620, iconType = "spell", name = "Enchant Gloves - Fishing", category = "Enchant", bonus = 2, minimumSkill = 1, source = "Enchanting" },
    },
    FISHING_QUEST_REWARDS = {
        { questID = 1580, name = "Electropellers", reward = "20 Aquadynamic Fish Lenses", rewardName = "Aquadynamic Fish Lens", rewardValue = "x20", rewardItemID = 6811, sourceLabel = "Electropellers", details = "Character level 12 and Fishing skill 10." },
        { questID = 1141, name = "The Family and the Fishing Pole", reward = "Blump Family Fishing Pole (+3 Fishing)", rewardName = "Blump Family Fishing Pole", rewardValue = "+3 Fishing", rewardItemID = 12225, sourceLabel = "Family and the Fishing Pole", details = "Fishing pole quest in Darkshore." },
        { questID = 7815, name = "Snapjaws, Mon!", reward = "Nat Pagle's Extreme Angler FC-5000 (+25 Fishing)", rewardName = "Extreme Angler FC-5000", rewardValue = "+25 Fishing", rewardItemID = 19022, side = "Horde", sourceLabel = "Snapjaws, Mon!", details = "Horde quest in the Hinterlands." },
        { questID = 8221, name = "Rare Fish: Keefer's Angelfish", reward = "Lucky Fishing Hat (+5 Fishing)", rewardName = "Lucky Fishing Hat", rewardValue = "+5 Fishing", rewardItemID = 19972, sourceLabel = "Keefer's Angelfish quest", details = "Reward for turning in Keefer's Angelfish." },
        { questID = 8225, name = "Rare Fish: Brownell's Blue Striped Racer", reward = "Nat Pagle's Extreme Anglin' Boots (+5 Fishing)", rewardName = "Extreme Anglin' Boots", rewardValue = "+5 Fishing", rewardItemID = 19969, sourceLabel = "Brownell's Racer quest", details = "Reward for turning in Brownell's Blue Striped Racer." },
        { questID = 8224, name = "Rare Fish: Dezian Queenfish", reward = "High Test Eternium Fishing Line (+5 Fishing)", rewardName = "Eternium Fishing Line", rewardValue = "+5 Fishing", rewardItemID = 19971, sourceLabel = "Dezian Queenfish quest", details = "Reward for turning in Dezian Queenfish." },
        { questID = 8193, name = "Master Angler", reward = "Arcanite Fishing Pole and Extravagant Extravaganza Coin. The coin can be exchanged for the Hook of the Master Angler and other tournament rewards.", rewardName = "Arcanite Fishing Pole", rewardValue = "Pole + coin", rewardItemID = 19970, sourceLabel = "Weekly; first 50 finishers", weekly = true, details = "The first 50 players to finish receive the Arcanite Fishing Pole and an Extravagant Extravaganza Coin. Exchange the coin for tournament rewards, including the Hook of the Master Angler." },
        { questID = 6607, name = "Nat Pagle, Angler Extreme", reward = "Artisan Fishing", rewardName = "Artisan Fishing", rewardValue = "Training", rewardSpellID = 18248, sourceLabel = "Artisan quest", requiredSkill = 225, requiredCharacterLevel = 35, details = "Catch four unique fish that are available only while on the quest." },
    },
    FISH_ALMANAC = {
        { id = 6291, name = "Raw Brilliant Smallfish", zone = "Elwynn Forest", mapID = 1429, habitat = "Low-level inland waters", zones = "Starter zones and capital-city waters", hint = "A common catch in low-level freshwater; availability varies by exact water.", source = "Wowhead Classic item 6291; Warcraft Wiki Fishing Locations" },
        { id = 6303, name = "Raw Slitherskin Mackerel", zone = "Durotar", mapID = 1411, habitat = "Low-level coastal waters", zones = "Coastal waters in low-level Azeroth zones", hint = "A common low-level saltwater catch. This entry marks a reported zone, not a precise pool.", source = "Wowhead Classic item 6303; Warcraft Wiki Fishing Locations" },
        { id = 6289, name = "Raw Longjaw Mud Snapper", zone = "Mulgore", mapID = 1412, habitat = "Low-level inland waters", zones = "Starter zones, capitals, and other low-level inland waters", hint = "A common catch in low-level freshwater; availability varies by exact water.", source = "Wowhead Classic item 6289; Warcraft Wiki Fishing Locations" },
        { id = 6361, name = "Raw Rainbow Fin Albacore", zone = "Wetlands", mapID = 1437, habitat = "Coastal waters", zones = "Ashenvale, Bloodmyst Isle, Darkshore, Durotar, Hillsbrad, Silverpine, Northern Barrens, Westfall, Wetlands", hint = "Reported in coastal waters across several low- and mid-level zones.", source = "Wowhead Classic item 6361; Warcraft Wiki Fishing Locations" },
        { id = 6317, name = "Raw Loch Frenzy", zone = "Loch Modan", mapID = 1432, habitat = "Loch Modan waters", zones = "Loch Modan", hint = "A location-specific catch from Loch Modan; the fish also drops from Loch Frenzy creatures.", source = "Wowhead Classic item 6317; Warcraft Wiki Fishing Locations" },
        { id = 21071, name = "Raw Sagefish", zone = "Ashenvale", mapID = 1440, habitat = "Inland waters", zones = "Ashenvale, Hillsbrad Foothills, Loch Modan, Silverpine Forest, Stonetalon Mountains", hint = "Reported in inland waters across these five zones.", source = "Wowhead Classic item 21071; Warcraft Wiki Fishing Locations" },
        { id = 6308, name = "Raw Bristle Whisker Catfish", zone = "Redridge Mountains", mapID = 1433, habitat = "Freshwater", zones = "Multiple low- and mid-level inland zones, including Loch Modan, Redridge, Westfall, and Wetlands", hint = "A broad freshwater catch; check your recorded spots for local results.", source = "Wowhead Classic item 6308; Warcraft Wiki Fishing Locations" },
        { id = 21153, name = "Raw Greater Sagefish", zone = "Hillsbrad Foothills", mapID = 1424, habitat = "Lordamere Lake and rivers", zones = "Lordamere Lake in Hillsbrad Foothills; rivers in Stranglethorn Vale; also listed for Moonglade", hint = "Reported from specific inland waters rather than every zone at this skill tier.", source = "Wowhead Classic item 21153; Warcraft Wiki Fishing Locations" },
        { id = 8365, name = "Raw Mithril Head Trout", zone = "Stranglethorn Vale", mapID = 1434, habitat = "Mid-level waters", zones = "Mid-level zones including Stranglethorn Vale, Desolace, and Arathi Highlands", hint = "A mid-level fish with availability that depends on the zone's water table.", source = "Wowhead Classic item 8365; Warcraft Wiki Fishing Locations" },
        { id = 6362, name = "Raw Rockscale Cod", zone = "Feralas", mapID = 1444, habitat = "Coastal waters", zones = "Coastal waters including Feralas, Stranglethorn Vale, Desolace, and Tanaris", hint = "Reported in mid-level coastal waters; some creatures also drop this fish.", source = "Wowhead Classic item 6362; Warcraft Wiki Fishing Locations" },
        { id = 13760, name = "Raw Sunscale Salmon", zone = "Feralas", mapID = 1444, habitat = "Inland waters; daytime", zones = "Feralas, Moonglade, Winterspring, Eastern and Western Plaguelands", hint = "Best reported during daytime. A few documented waters have exceptions to the usual time window.", source = "Wowhead Classic item 13760; Warcraft Wiki Fishing Locations" },
        { id = 13759, name = "Raw Nightfin Snapper", zone = "Feralas", mapID = 1444, habitat = "Inland waters; nighttime", zones = "Feralas, Moonglade, Winterspring, Plaguelands, Felwood, and other high-level inland waters", hint = "Usually caught from 6 PM to 6 AM server time; documented local exceptions exist.", source = "Wowhead Classic item 13759; Warcraft Wiki Fishing Locations" },
        { id = 13754, name = "Raw Glossy Mightfish", zone = "Tanaris", mapID = 1446, habitat = "Coastal waters", zones = "Azshara, Badlands, Feralas, Stranglethorn Vale, Tanaris, and the Hinterlands", hint = "A high-level coastal fish; published availability is zone-level, not an exact shore coordinate.", source = "Wowhead Classic item 13754; Warcraft Wiki Fishing Locations" },
        { id = 13893, name = "Large Raw Mightfish", zone = "Swamp of Sorrows", mapID = 1435, habitat = "Open seawater", zones = "Swamp of Sorrows and Blasted Lands", hint = "Reported from open seawater in these two zones; high Fishing skill is recommended.", source = "Wowhead Classic item 13893; Warcraft Wiki Fishing Locations" },
        { id = 13755, name = "Winter Squid", zone = "Swamp of Sorrows", mapID = 1435, habitat = "Coastal waters; winter", zones = "Blasted Lands, Swamp of Sorrows, Badlands, Eastern Plaguelands, Tanaris, and Thousand Needles", hint = "Seasonal catch available in winter; it shares reported waters with Summer Bass.", source = "Wowhead Classic item 13755; Warcraft Wiki Fishing Locations" },
        { id = 13756, name = "Raw Summer Bass", zone = "Swamp of Sorrows", mapID = 1435, habitat = "Coastal waters; summer", zones = "Blasted Lands, Swamp of Sorrows, Badlands, Eastern Plaguelands, Tanaris, and Thousand Needles", hint = "Seasonal catch available in summer; it shares reported waters with Winter Squid.", source = "Wowhead Classic item 13756; Warcraft Wiki Fishing Locations" },
        { id = 13758, name = "Raw Redgill", zone = "Eastern Plaguelands", mapID = 1423, habitat = "Inland waters", zones = "Un'Goro Crater, Silithus, Plaguelands, Azshara, Felwood, Moonglade, and other high-level waters", hint = "A high-level inland fish; published zone coverage is approximate.", source = "Wowhead Classic item 13758; Warcraft Wiki Fishing Locations" },
        { id = 4603, name = "Raw Spotted Yellowtail", zone = "Tanaris", mapID = 1446, habitat = "Saltwater", zones = "Saltwater including Tanaris, Desolace, Feralas, and Stranglethorn Vale", hint = "Reported in saltwater; it can also drop from humanoid creatures.", source = "Wowhead Classic item 4603; Warcraft Wiki Fishing Locations" },
        { id = 13888, name = "Darkclaw Lobster", zone = "Azshara", mapID = 1447, habitat = "Bay of Storms and Blasted Lands coast", zones = "Bay of Storms in Azshara and coastal Blasted Lands", hint = "A high-level coastal catch. Exact local spots are learned from recorded catches.", source = "Wowhead Classic item 13888; Warcraft Wiki Fishing Locations" },
        { id = 13889, name = "Raw Whitescale Salmon", zone = "Winterspring", mapID = 1452, habitat = "High-level inland waters", zones = "Winterspring, Zul'Gurub, Eastern Plaguelands, Feralas, Silithus, and Burning Steppes", hint = "Reported from high-level inland waters.", source = "Wowhead Classic item 13889; Warcraft Wiki Fishing Locations" },
        { id = 6358, name = "Oily Blackmouth", zone = "Westfall", mapID = 1436, habitat = "Coastal waters and some lakes", zones = "Stranglethorn Vale, Darkshore, Azshara, Westfall, Wetlands, and Eastern Plaguelands", hint = "Alchemy fish reported across several coastal and inland locations.", source = "Wowhead Classic item 6358; Warcraft Wiki Fishing Locations" },
        { id = 6359, name = "Firefin Snapper", zone = "Wetlands", mapID = 1437, habitat = "Coastal waters", zones = "Arathi Highlands, Stranglethorn Vale, Ashenvale, Azshara, Westfall, Wetlands, Desolace, and Dustwallow Marsh", hint = "Alchemy fish reported from coastal waters across several zones.", source = "Wowhead Classic item 6359; Warcraft Wiki Fishing Locations" },
        { id = 13422, name = "Stonescale Eel", zone = "Tanaris", mapID = 1446, habitat = "High-level coastal waters", zones = "Tanaris, Thousand Needles, Feralas, and other high-level coastal waters", hint = "A high-level alchemy fish; time and location can affect observed catches.", source = "Wowhead Classic item 13422; Warcraft Wiki Fishing Locations" },
        { id = 6522, name = "Deviate Fish", zone = "Northern Barrens", mapID = 1413, habitat = "Oases and Wailing Caverns", zones = "Northern Barrens oases and Wailing Caverns", hint = "A distinctive location-specific catch from oasis water and Wailing Caverns.", source = "Wowhead Classic item 6522; Warcraft Wiki Fishing Locations" },
        { id = 16967, name = "Feralas Ahi", zone = "Feralas", mapID = 1444, habitat = "Verdantis River", zones = "Verdantis River, west of Camp Mojache", hint = "Quest fish. Exact hotspots appear after recorded catches.", source = "Nat Pagle, Angler Extreme; Wowhead Classic item 16967" },
        { id = 16970, name = "Misty Reed Mahi Mahi", zone = "Swamp of Sorrows", mapID = 1435, habitat = "Misty Reed Strand", zones = "Eastern shore of the Swamp of Sorrows", hint = "Quest fish. Exact hotspots appear after recorded catches.", source = "Nat Pagle, Angler Extreme; Wowhead Classic item 16970" },
        { id = 16968, name = "Sar'theris Striker", zone = "Desolace", mapID = 1443, habitat = "Sar'theris Strand", zones = "Sar'theris Strand, south of Shadowprey Village", hint = "Quest fish. Exact hotspots appear after recorded catches.", source = "Nat Pagle, Angler Extreme; Wowhead Classic item 16968" },
        { id = 16969, name = "Savage Coast Blue Sailfin", zone = "Stranglethorn Vale", mapID = 1434, habitat = "Savage Coast", zones = "Savage Coast in Stranglethorn Vale", hint = "Quest fish. Exact hotspots appear after recorded catches.", source = "Nat Pagle, Angler Extreme; Wowhead Classic item 16969" },
        { id = 19805, name = "Keefer's Angelfish", zone = "Stranglethorn Vale", mapID = 1434, habitat = "Schools of Tastyfish during the Extravaganza", zones = "Northern Stranglethorn and Cape of Stranglethorn during the weekly event", hint = "Rare contest fish caught from Schools of Tastyfish during the event.", source = "Stranglethorn Fishing Extravaganza; Wowhead item 19805" },
        { id = 19806, name = "Dezian Queenfish", zone = "Stranglethorn Vale", mapID = 1434, habitat = "Schools of Tastyfish during the Extravaganza", zones = "Northern Stranglethorn and Cape of Stranglethorn during the weekly event", hint = "Rare contest fish caught from Schools of Tastyfish during the event.", source = "Stranglethorn Fishing Extravaganza; Wowhead item 19806" },
        { id = 19803, name = "Brownell's Blue Striped Racer", zone = "Stranglethorn Vale", mapID = 1434, habitat = "Schools of Tastyfish during the Extravaganza", zones = "Northern Stranglethorn and Cape of Stranglethorn during the weekly event", hint = "Rare contest fish caught during the Stranglethorn Fishing Extravaganza.", source = "Stranglethorn Fishing Extravaganza; Wowhead item 19803" },
        { id = 19807, name = "Speckled Tastyfish", zone = "Stranglethorn Vale", mapID = 1434, habitat = "Fishing pools during the Extravaganza", zones = "Northern Stranglethorn and Cape of Stranglethorn during the weekly event", hint = "Caught from fishing pools in the event area while the contest is active.", source = "Stranglethorn Fishing Extravaganza; Wowhead item 19807" },
    },
    CHAT_GEAR_SLOT_IDS = { 16, 1, 10, 8, 17 },
}